"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-28 01:35:58.622263+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("abn", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("payment_instructions", sa.Text(), nullable=True),
        sa.Column("bank_account_name", sa.String(length=200), nullable=True),
        sa.Column("bank_bsb", sa.String(length=10), nullable=True),
        sa.Column("bank_account_number", sa.String(length=20), nullable=True),
        sa.Column("gst_registered", sa.Boolean(), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("financial_year_start_month", sa.Integer(), nullable=False),
        sa.Column("default_terms_days", sa.Integer(), nullable=False),
        sa.Column("invoice_footer", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("default_terms_days >= 0", name="ck_business_profiles_terms"),
        sa.CheckConstraint(
            "financial_year_start_month BETWEEN 1 AND 12", name="ck_business_profiles_fy_month"
        ),
        sa.CheckConstraint("gst_rate >= 0", name="ck_business_profiles_gst_rate"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("type IN ('income', 'expense', 'service')", name="ck_categories_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "name", name="uq_categories_type_name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("ix_categories_type", ["type"], unique=False)

    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=True),
        sa.Column("abn", sa.String(length=20), nullable=True),
        sa.Column("contact_name", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("default_terms_days", sa.Integer(), nullable=True),
        sa.Column("default_notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "default_terms_days IS NULL OR default_terms_days >= 0", name="ck_clients_terms"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_index("ix_clients_display_name", ["display_name"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("managed_relative_path", sa.Text(), nullable=True),
        sa.Column("external_path", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("missing_last_checked", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "managed_relative_path IS NOT NULL OR external_path IS NOT NULL",
            name="ck_documents_has_location",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_documents_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_documents_sha256", ["sha256"], unique=False)

    op.create_table(
        "number_sequences",
        sa.Column("sequence_type", sa.String(length=20), nullable=False),
        sa.Column("prefix", sa.String(length=10), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.Column("padding", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("next_value >= 1", name="ck_number_sequences_next_value"),
        sa.CheckConstraint("padding >= 1", name="ck_number_sequences_padding"),
        sa.PrimaryKeyConstraint("sequence_type"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("before_json", sa.Text(), nullable=True),
        sa.Column("after_json", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_events_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_audit_events_timestamp_utc", ["timestamp_utc"], unique=False)

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_number", sa.String(length=40), nullable=True),
        sa.Column("original_number", sa.String(length=40), nullable=True),
        sa.Column("status_override", sa.String(length=20), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("client_name_snapshot", sa.String(length=200), nullable=True),
        sa.Column("client_abn_snapshot", sa.String(length=20), nullable=True),
        sa.Column("client_contact_snapshot", sa.String(length=120), nullable=True),
        sa.Column("client_email_snapshot", sa.String(length=200), nullable=True),
        sa.Column("client_phone_snapshot", sa.String(length=40), nullable=True),
        sa.Column("client_address_snapshot", sa.Text(), nullable=True),
        sa.Column("business_name_snapshot", sa.String(length=200), nullable=True),
        sa.Column("business_abn_snapshot", sa.String(length=20), nullable=True),
        sa.Column("business_address_snapshot", sa.Text(), nullable=True),
        sa.Column("business_phone_snapshot", sa.String(length=40), nullable=True),
        sa.Column("business_email_snapshot", sa.String(length=200), nullable=True),
        sa.Column("payment_instructions_snapshot", sa.Text(), nullable=True),
        sa.Column("gst_registered_snapshot", sa.Boolean(), nullable=False),
        sa.Column("gst_rate_snapshot", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("visible_notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("footer_snapshot", sa.Text(), nullable=True),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("gst_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status_override IS NULL OR status_override IN ('Draft', 'Cancelled', 'Void')",
            name="ck_invoices_status_override",
        ),
        sa.CheckConstraint("gst_cents >= 0", name="ck_invoices_gst"),
        sa.CheckConstraint(
            "issued_at IS NULL OR canonical_number IS NOT NULL",
            name="ck_invoices_issued_has_number",
        ),
        sa.CheckConstraint("subtotal_cents >= 0", name="ck_invoices_subtotal"),
        sa.CheckConstraint("total_cents >= 0", name="ck_invoices_total"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_number"),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index("ix_invoices_client_id", ["client_id"], unique=False)
        batch_op.create_index("ix_invoices_due_date", ["due_date"], unique=False)
        batch_op.create_index("ix_invoices_invoice_date", ["invoice_date"], unique=False)
        batch_op.create_index("ix_invoices_reference", ["reference"], unique=False)

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ex_gst_cents", sa.Integer(), nullable=False),
        sa.Column("gst_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("supplier_payee", sa.String(length=200), nullable=True),
        sa.Column("payment_method", sa.String(length=40), nullable=True),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("type IN ('income', 'expense')", name="ck_ledger_entries_type"),
        sa.CheckConstraint(
            "reversed_at IS NULL OR reversal_reason IS NOT NULL",
            name="ck_ledger_entries_reversal_reason",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index("ix_ledger_entries_category_id", ["category_id"], unique=False)
        batch_op.create_index("ix_ledger_entries_entry_date", ["entry_date"], unique=False)

    op.create_table(
        "migration_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("source_description", sa.Text(), nullable=False),
        sa.Column("source_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=True),
        sa.Column("counts_json", sa.Text(), nullable=True),
        sa.Column("report_document_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("unit_price_cents >= 0", name="ck_service_items_price"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "credit_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_number", sa.String(length=40), nullable=False),
        sa.Column("original_number", sa.String(length=40), nullable=True),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("credit_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("gst_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("total_cents >= 0", name="ck_credit_notes_total"),
        sa.CheckConstraint(
            "voided_at IS NULL OR void_reason IS NOT NULL", name="ck_credit_notes_void_reason"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_number"),
    )
    with op.batch_alter_table("credit_notes", schema=None) as batch_op:
        batch_op.create_index("ix_credit_notes_invoice_id", ["invoice_id"], unique=False)

    op.create_table(
        "invoice_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("service_item_id", sa.Integer(), nullable=True),
        sa.Column("service_code_snapshot", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity_decimal", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("discount_type", sa.String(length=10), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("gst_rate_decimal", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("gst_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "discount_type IN ('none', 'fixed', 'percent')", name="ck_invoice_items_discount_type"
        ),
        sa.CheckConstraint("discount_cents >= 0", name="ck_invoice_items_discount"),
        sa.CheckConstraint("gst_cents >= 0", name="ck_invoice_items_gst"),
        sa.CheckConstraint("quantity_decimal >= 0", name="ck_invoice_items_quantity"),
        sa.CheckConstraint("unit_price_cents >= 0", name="ck_invoice_items_price"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["service_item_id"],
            ["service_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "position", name="uq_invoice_items_position"),
    )
    op.create_table(
        "migration_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("issue_code", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=True),
        sa.Column("source_key", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("proposed_resolution", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error')", name="ck_migration_issues_severity"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["migration_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("migration_issues", schema=None) as batch_op:
        batch_op.create_index("ix_migration_issues_run_id", ["run_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=True),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("reversed_at", sa.DateTime(), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("amount_cents > 0", name="ck_payments_amount"),
        sa.CheckConstraint(
            "reversed_at IS NULL OR reversal_reason IS NOT NULL", name="ck_payments_reversal_reason"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_invoice_id", ["invoice_id"], unique=False)
        batch_op.create_index("ix_payments_payment_date", ["payment_date"], unique=False)

    op.create_table(
        "credit_note_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credit_note_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity_decimal", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("gst_rate_decimal", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("gst_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["credit_note_id"], ["credit_notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credit_note_id", "position", name="uq_credit_note_items_position"),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_number", sa.String(length=40), nullable=False),
        sa.Column("original_number", sa.String(length=40), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_number"),
        sa.UniqueConstraint("payment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipts")
    op.drop_table("credit_note_items")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index("ix_payments_payment_date")
        batch_op.drop_index("ix_payments_invoice_id")

    op.drop_table("payments")
    with op.batch_alter_table("migration_issues", schema=None) as batch_op:
        batch_op.drop_index("ix_migration_issues_run_id")

    op.drop_table("migration_issues")
    op.drop_table("invoice_items")
    with op.batch_alter_table("credit_notes", schema=None) as batch_op:
        batch_op.drop_index("ix_credit_notes_invoice_id")

    op.drop_table("credit_notes")
    op.drop_table("service_items")
    op.drop_table("migration_runs")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_entries_entry_date")
        batch_op.drop_index("ix_ledger_entries_category_id")

    op.drop_table("ledger_entries")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index("ix_invoices_reference")
        batch_op.drop_index("ix_invoices_invoice_date")
        batch_op.drop_index("ix_invoices_due_date")
        batch_op.drop_index("ix_invoices_client_id")

    op.drop_table("invoices")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_timestamp_utc")
        batch_op.drop_index("ix_audit_events_entity")

    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("number_sequences")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_sha256")
        batch_op.drop_index("ix_documents_entity")

    op.drop_table("documents")
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index("ix_clients_display_name")

    op.drop_table("clients")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("ix_categories_type")

    op.drop_table("categories")
    op.drop_table("business_profiles")
    # ### end Alembic commands ###
